# Generated by Django 5.2.1 on 2025-05-22 18:33

from django.db import migrations
from django.utils.text import slugify

def load_initial_tech_data(apps, schema_editor):
    TechCategory = apps.get_model('job', 'TechCategory')
    TechStack = apps.get_model('job', 'TechStack')

    tech_data = {
        "Backend Development": ["Java", ".NET", "PHP", "C/C++/Embedded", "Python", "Ruby", "Go", "Node.js"],
        "Frontend Development": ["JavaScript", "React", "Angular", "Vue.js"],
        "Fullstack Development": ["FullStack Developer"],
        "Infrastructure": ["DevOps", "Database Engineer", "Cybersecurity", "SysAdmin"],
        "Quality Assurance": ["Automation QA", "Manual QA"],
        "Data Science": ["ETL/Data warehouse", "Big Data", "BI/Data visualization", "ML/AI/Data modelling"],
        "ERP / CRM Development": ["SAP", "SalesForce"],
        "Mobile Development": ["iOS", "Android"],
        "PM/BA and more": ["IT Project Management", "IT Business Analyst", "Product Management", "Product Owner", "Tech Writer"],
        "Hardware and Engineering": ["Hardware and Engineering"],
        "Customer Support": ["Customer Support"],
        "Technical Support": ["Technical Support"],
        "UI/UX, Arts": ["UI/UX"],
    }

    for category_name, techs in tech_data.items():
        category, _ = TechCategory.objects.get_or_create(name=category_name)
        for tech_name in techs:
            TechStack.objects.get_or_create(
                name=tech_name,
                category=category,
                slug=slugify(tech_name)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_techcategory_remove_job_tech_stack_techstack_and_more'),
    ]

    operations = [
        migrations.RunPython(load_initial_tech_data),
    ]
