# Generated by Django 5.2.1 on 2025-05-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20250522_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
