# Generated by Django 5.2.1 on 2025-05-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_techstack_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='slug',
            field=models.SlugField(default='empty', max_length=100, unique=True),
        ),
    ]
