# Generated by Django 5.2.1 on 2025-06-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
