export const TECH_STACKS = [
    { id: 1, name: "Java", slug: "java" },
    { id: 2, name: ".NET", slug: "net" },
    { id: 3, name: "PHP", slug: "php" },
    { id: 4, name: "C/C++/Embedded", slug: "ccembedded" },
    { id: 5, name: "Python", slug: "python" },
    { id: 6, name: "Ruby", slug: "ruby" },
    { id: 7, name: "Go", slug: "go" },
    { id: 8, name: "Node.js", slug: "nodejs" },
    { id: 9, name: "JavaScript", slug: "javascript" },
    { id: 10, name: "React", slug: "react" },
    { id: 11, name: "Angular", slug: "angular" },
    { id: 12, name: "Vue.js", slug: "vuejs" },
    { id: 13, name: "DevOps", slug: "devops" },
    { id: 14, name: "Database Engineer", slug: "database-engineer" },
    { id: 15, name: "Cybersecurity", slug: "cybersecurity" },
    { id: 16, name: "SysAdmin", slug: "sysadmin" },
    { id: 17, name: "Automation QA", slug: "automation-qa" },
    { id: 18, name: "Manual QA", slug: "manual-qa" },
    { id: 19, name: "ETL/Data warehouse", slug: "etldata-warehouse" },
    { id: 20, name: "Big Data", slug: "big-data" },
    { id: 21, name: "BI/Data visualization", slug: "bidata-visualization" },
    { id: 22, name: "ML/AI/Data modelling", slug: "mlaidata-modelling" },
    { id: 23, name: "SAP", slug: "sap" },
    { id: 24, name: "SalesForce", slug: "salesforce" },
    { id: 25, name: "iOS", slug: "ios" },
    { id: 26, name: "Android", slug: "android" },
    { id: 27, name: "IT Project Management", slug: "it-project-management" },
    { id: 28, name: "IT Business Analyst", slug: "it-business-analyst" },
    { id: 29, name: "Product Management", slug: "product-management" },
    { id: 30, name: "Product Owner", slug: "product-owner" },
    { id: 31, name: "Tech Writer", slug: "tech-writer" },
    { id: 32, name: "FullStack Developer", slug: "fullstack-developer" },
    { id: 33, name: "Hardware and Engineering", slug: "hardware-and-engineering" },
    { id: 34, name: "Customer Support", slug: "customer-support" },
    { id: 35, name: "Technical Support", slug: "technical-support" },
    { id: 36, name: "UI/UX", slug: "ui-ux" },
];
