# Generated by Django 5.2.1 on 2025-05-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('interviewer', 'Interviewer')], default='candidate', max_length=20),
        ),
    ]
